version: '3.5'
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: "mssql"
    ports:
      - "1433:1433"
    volumes:
      - /mnt/mssqlsystem:/var/opt/mssql/data
      - /mnt/mssqluser:/var/opt/sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=2wsx2WSX
      - MSSQL_LOG_DIR=/var/opt/sqlserver
      - MSSQL_DATA_DIR=/var/opt/sqlserver
    restart: always
    
  programbeaverhut:
    image: diwars/programbeaverhutru001:latest
    container_name: "programbeaverhut"
    environment:
      - ASPNETCORE_ENVIRONMENT=production
    ports:
      - "8080:80"
      - "8443:443"
    restart: always
    depends_on:
      - mssql
