version: '3.5'
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: "mssql"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=2wsx2WSX
    restart: always
    volumes:
      - data:/var/opt/mssql/data
      - log:/var/opt/mssql/log
      - secrets:/var/opt/mssql/secrets
  programbeaverhut:
    image: diwars/programbeaverhutru001:latest
    container_name: "programbeaverhut"
    environment:
      - ASPNETCORE_ENVIRONMENT=production
    ports:
      - "8080:80"
      - "8443:443"
    restart: always
volumes:
  data:
  log:
  secrets: